Running 컴포넌트 솔로
totally-amazing/zombierun-frontend pull request #21
Opened 2022-02-11 14:09 UTC by Vaatz95

# 러닝 컴포넌트 솔로 

## 노션 칸반 링크

- [[FrontEnd] Running 컴포넌트 작성](https://www.notion.so/vanillacoding/FrontEnd-Running-048b13bb6d9e408c97e20fccb21c8c78)

## 구현사항
- 상단에 톱니 바퀴를 누르면 소리 설정과 게임 종료 버튼이 나타납니다
- 톱니 바퀴 버튼을 클릭 시에 게임의 진행 상황이 일시정지합니다
- 옵션 부분에서 소리 설정을 토글 할 수 있습니다.
- 소리 설정을 토클 한 것에 기반으로 해당 소리가 나거나 나지 않습니다
- 전체적인 UI 디자인이 목업과 유사하게 구현되었습니다.
- 처음 게임 시작 시에 5초 지연 시간 동안 메시지가 표시 됩니다.
- 이후에 게임을 일시정지 할 시에 Play 버튼 아이콘이 나타납니다.
- 정지 시에 스톱 버튼이 사라집니다.
- 게임 관련 화면의 컴포넌트를 따로 분리했습니다.

## 테스트 방법

- 안드로이드 휴대폰을 활용해 직접 해당 사항 체크

## 보완해야할 점

- 현재 일시 정지 시에 좀비가 정지하는 부분은 아쉽게 구현하지 못했습니다.
- 처음 게임 시작 시에 카운트 다운을 구현하지 못했습니다.

2022-02-11 14:34 UTC, hyemin916 requested changes
전반적으로 리팩토링도 잘해주셨고 복잡한 기능도 구현하시느라 수고하셨습니다!

2022-02-11 14:34 UTC, hyemin916 commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
true로 설정해주시는게 좋을 듯 합니다

2022-02-11 14:34 UTC, hyemin916 commented on screen/Running/RunningScreen.js
> +    if (!hasSwitchSoundEffectOption) {
canHearingBGMusic이라는 전역 상태가 false인데 사운드가 플레이 되는 이유가 궁금합니다

2022-02-11 14:34 UTC, hyemin916 commented on screen/Running/RunningScreen.js
> +    pauseGameStatus();
pauseGameStatus라는 함수를 스탑 버튼을 누를때와 옵션 버튼을 누를때 사용할 수 있군요👍

2022-02-11 14:34 UTC, hyemin916 commented on screen/Running/RunningScreen.js
> +  useEffect(() => {
각각의 useEffect들은 어떤 기준으로 나누셨을까요? 각 useEffect의 주제를 쉽게 알 수 있게 useEffect 내부의 코드들을 함수로 한번 감싸도 좋을 것 같습니다

2022-02-11 14:34 UTC, hyemin916 commented on screen/Running/RunningScreen.js
> +    return () => {
interval을 clear하시네요👍 그런데 리액트 컴포넌트에서 setInterval은 예상대로 작동되지 않기도 하는데, 관련 글 링크 첨부합니다 참고만 하셔도 좋을 것 같습니다
https://velog.io/@jakeseo_me/번역-리액트-훅스-컴포넌트에서-setInterval-사용-시의-문제점

2022-02-11 14:41 UTC, Vaatz95 commented on store/index.js
> -    game: gameReducer,
현재 merge 받은 상태에 제 브랜치에는 정상적으로 파일이 있습니다. 다시 한번 add 해서 체크해보겠습니다.

2022-02-11 14:43 UTC, Vaatz95 commented on screen/Running/RunningScreen.js
> +    if (!hasSwitchSoundEffectOption) {
직관적인 의미의 변수 선언에 따른 Bool 선언을 고려하지 못하면서 네이밍 부분과 괴리감이 발생한거 같습니다. 바로 수정하겠습니다.

2022-02-11 14:48 UTC, Vaatz95 commented on screen/Running/RunningScreen.js
> +  useEffect(() => {
전반적으로 처음의 초기 설정 / 게임 시작시 좀비의 이동 / 그리고 결과 판단 으로 나누어 놨습니다. 좀 더 가독성 있게 안에 함수로 한번 더 감싸서 명시 해놓겠습니다. 감사합니다 ☺️

2022-02-11 15:35 UTC, yohrran approved these changes
완모님 러닝 컴포넌트 부분을 리팩토링 잘 해주신 것 같습니다 특히 변수명과 컴포넌트를 나눠주시는 부분들 깔끔하고 더 좋아졌네요! 수고하셨습니다!

2022-02-11 15:35 UTC, yohrran commented on screen/Running/RunningScreen.js
> +    setHasOptionClicked(true);
러닝 컴포넌트에서 버튼을 누르는 부분들이 많았는데 그런 부분들을 잘 고려해주신 것 같습니다

2022-02-11 15:35 UTC, yohrran commented on screen/Running/audioController.js
> +    this.soundEffectAudio.loadAsync(this.soundEffectSource, {
클래스 부분을 잘 짜주신 것 같아요 추후 사용자가 어디서든 음악을 다시 키고, 끄고가 가능 할 것 같습니다

2022-02-11 15:35 UTC, yohrran commented on screen/Running/components/Pause.js
> +    color: COLORS.DEEP_RED,
다른 파일에서는 color가 아래쪽에 위치하는데 이 부분은 위쪽이네요

2022-02-11 15:35 UTC, yohrran commented on screen/Setting/SettingScreen.js
> +      <StandardModal onClose={onClose}>
onClose부분을 Modal까지 내려주면서 코드를 좀 더 깔끔하게 수정시켜주셨네요 세팅부분과 함께 동작하는 부분을 잘 바꿔주신 것 같습니다

2022-02-11 15:57 UTC, Vaatz95 commented on screen/Running/RunningScreen.js
> +    pauseGameStatus();
반복 되는 함수 로직이라 하나의 함수로 묶어서 처리하고 각각 버튼 기능에 할당해주었습니다.

2022-02-12 01:27 UTC, hyemin916 approved these changes

2022-02-12 03:29 UTC, merged